version: '3.1'
services:
  rsm-msba:
    image: "vnijs/rsm-msba"
    ports:
      - 80:80
      - 8787:8787
      - 8888:8888
    volumes:
      - ~:/home/rstudio

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    volumes:
       - ~/postgresql/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - 5050:80
    restart: always
    volumes:
       - ~/postgresql/pgadmin:/var/lib/pgadmin
